version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ciphers
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - ciphers-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ciphers-redis:/var/lib/redis/data

  ciphers:
    build:
      context: .
    volumes:
      - ./ciphers:/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  sidekiq:
    depends_on:
      - ciphers
      - postgres
      - redis
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  ciphers-postgres:
  ciphers-redis: